DROP DATABASE IF EXISTS Todo;
CREATE DATABASE Todo;

USE Todo;

CREATE TABLE Todo (
    TodoId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  
    Name VARCHAR(255) NOT NULL,
    Completed BOOL NOT NULL DEFAULT 0
);

INSERT INTO Todo (NAME, COMPLETED) VALUES ('Buy milk', 0);
INSERT INTO Todo (NAME, COMPLETED) VALUES ('Buy eggs', 0);
INSERT INTO Todo (NAME, COMPLETED) VALUES ('Create Assignments', 0);
INSERT INTO Todo (NAME, COMPLETED) VALUES ('Test Assignments', 0);